//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NutriNET.Maui.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NutriNET.Maui.Resources.Languages.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        internal static string Accept {
            get {
                return ResourceManager.GetString("Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action not allowed.
        /// </summary>
        internal static string ActionNotAllowed {
            get {
                return ResourceManager.GetString("ActionNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrators cannot delete themselves..
        /// </summary>
        internal static string AdminCannotDeleteSelf {
            get {
                return ResourceManager.GetString("AdminCannotDeleteSelf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All fields are required..
        /// </summary>
        internal static string AllFieldsRequiredMessage {
            get {
                return ResourceManager.GetString("AllFieldsRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User already has active restriction.
        /// </summary>
        internal static string AlreadyHasRestriction {
            get {
                return ResourceManager.GetString("AlreadyHasRestriction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already have an account? Log in.
        /// </summary>
        internal static string AlreadyHaveAccountText {
            get {
                return ResourceManager.GetString("AlreadyHaveAccountText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barcode.
        /// </summary>
        internal static string Barcode {
            get {
                return ResourceManager.GetString("Barcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No food with barcode {0} was found.
        /// </summary>
        internal static string BarcodeNotFound {
            get {
                return ResourceManager.GetString("BarcodeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand.
        /// </summary>
        internal static string Brand {
            get {
                return ResourceManager.GetString("Brand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breakfast.
        /// </summary>
        internal static string Breakfast {
            get {
                return ResourceManager.GetString("Breakfast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By.
        /// </summary>
        internal static string By {
            get {
                return ResourceManager.GetString("By", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calories.
        /// </summary>
        internal static string Calories {
            get {
                return ResourceManager.GetString("Calories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot delete another administrator.
        /// </summary>
        internal static string CannotDeleteOtherAdmin {
            get {
                return ResourceManager.GetString("CannotDeleteOtherAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carbs.
        /// </summary>
        internal static string Carbohydrates {
            get {
                return ResourceManager.GetString("Carbohydrates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Email.
        /// </summary>
        internal static string ChangeEmail {
            get {
                return ResourceManager.GetString("ChangeEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        internal static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        internal static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code sent! Check your email!.
        /// </summary>
        internal static string CodeSent {
            get {
                return ResourceManager.GetString("CodeSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment restriction not found..
        /// </summary>
        internal static string CommentRestrictionNotFound {
            get {
                return ResourceManager.GetString("CommentRestrictionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No restrictions found.
        /// </summary>
        internal static string CommentRestrictionsEmpty {
            get {
                return ResourceManager.GetString("CommentRestrictionsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment Restrictions.
        /// </summary>
        internal static string CommentRestrictionsPageTitle {
            get {
                return ResourceManager.GetString("CommentRestrictionsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restriction Status.
        /// </summary>
        internal static string CommentRestrictionsPickerTitle {
            get {
                return ResourceManager.GetString("CommentRestrictionsPickerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Delete ({0} of {1}).
        /// </summary>
        internal static string ConfirmDeleteProgressTitle {
            get {
                return ResourceManager.GetString("ConfirmDeleteProgressTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Account.
        /// </summary>
        internal static string CreateAccountText {
            get {
                return ResourceManager.GetString("CreateAccountText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} created.
        /// </summary>
        internal static string Created {
            get {
                return ResourceManager.GetString("Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} created.
        /// </summary>
        internal static string CreatedFood {
            get {
                return ResourceManager.GetString("CreatedFood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Food.
        /// </summary>
        internal static string CreateFoodTitle {
            get {
                return ResourceManager.GetString("CreateFoodTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Moderator.
        /// </summary>
        internal static string CreateModeratorRequestPageTitle {
            get {
                return ResourceManager.GetString("CreateModeratorRequestPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Email.
        /// </summary>
        internal static string CurrentEmail {
            get {
                return ResourceManager.GetString("CurrentEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current password.
        /// </summary>
        internal static string CurrentPassword {
            get {
                return ResourceManager.GetString("CurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decline.
        /// </summary>
        internal static string Decline {
            get {
                return ResourceManager.GetString("Decline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} deleted.
        /// </summary>
        internal static string DeletedFood {
            get {
                return ResourceManager.GetString("DeletedFood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} deleted.
        /// </summary>
        internal static string DeletedUser {
            get {
                return ResourceManager.GetString("DeletedUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete your account? This action cannot be undone..
        /// </summary>
        internal static string DeleteMyAccountConfirmMessage {
            get {
                return ResourceManager.GetString("DeleteMyAccountConfirmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete {0}.
        /// </summary>
        internal static string DeleteName {
            get {
                return ResourceManager.GetString("DeleteName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete {0}?.
        /// </summary>
        internal static string DeleteNameMessage {
            get {
                return ResourceManager.GetString("DeleteNameMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demote.
        /// </summary>
        internal static string Demote {
            get {
                return ResourceManager.GetString("Demote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} demoted.
        /// </summary>
        internal static string Demoted {
            get {
                return ResourceManager.GetString("Demoted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to demote this moderator to a normal user?.
        /// </summary>
        internal static string DemoteMessage {
            get {
                return ResourceManager.GetString("DemoteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demote {0}.
        /// </summary>
        internal static string DemoteTitle {
            get {
                return ResourceManager.GetString("DemoteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dinner.
        /// </summary>
        internal static string Dinner {
            get {
                return ResourceManager.GetString("Dinner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address.
        /// </summary>
        internal static string EmailAddress {
            get {
                return ResourceManager.GetString("EmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email updated.
        /// </summary>
        internal static string EmailUpdated {
            get {
                return ResourceManager.GetString("EmailUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is already in use..
        /// </summary>
        internal static string EmailUse {
            get {
                return ResourceManager.GetString("EmailUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End.
        /// </summary>
        internal static string End {
            get {
                return ResourceManager.GetString("End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End.
        /// </summary>
        internal static string EndButton {
            get {
                return ResourceManager.GetString("EndButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to end {0}&apos;s restriction?.
        /// </summary>
        internal static string EndUserRestrictionConfirmation {
            get {
                return ResourceManager.GetString("EndUserRestrictionConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fat.
        /// </summary>
        internal static string Fat {
            get {
                return ResourceManager.GetString("Fat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow.
        /// </summary>
        internal static string Follow {
            get {
                return ResourceManager.GetString("Follow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow Back.
        /// </summary>
        internal static string FollowBack {
            get {
                return ResourceManager.GetString("FollowBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have no followers yet.
        /// </summary>
        internal static string FollowersEmpty {
            get {
                return ResourceManager.GetString("FollowersEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Followers.
        /// </summary>
        internal static string FollowersPageTitle {
            get {
                return ResourceManager.GetString("FollowersPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You’re not following anyone.
        /// </summary>
        internal static string FollowingEmpty {
            get {
                return ResourceManager.GetString("FollowingEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Following.
        /// </summary>
        internal static string FollowingPageTitle {
            get {
                return ResourceManager.GetString("FollowingPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Food with barcode {0} already exists..
        /// </summary>
        internal static string FoodBarcodeExists {
            get {
                return ResourceManager.GetString("FoodBarcodeExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No foods found.
        /// </summary>
        internal static string FoodCatalogEmpty {
            get {
                return ResourceManager.GetString("FoodCatalogEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Food Catalog.
        /// </summary>
        internal static string FoodCatalogPageTitle {
            get {
                return ResourceManager.GetString("FoodCatalogPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search food by name or brand.
        /// </summary>
        internal static string FoodCatalogSearch {
            get {
                return ResourceManager.GetString("FoodCatalogSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catalog.
        /// </summary>
        internal static string FoodCatalogTabPageTitle {
            get {
                return ResourceManager.GetString("FoodCatalogTabPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Food not found.
        /// </summary>
        internal static string FoodNotFound {
            get {
                return ResourceManager.GetString("FoodNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request for {0} created.
        /// </summary>
        internal static string FoodRequestCreated {
            get {
                return ResourceManager.GetString("FoodRequestCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Food with barcode {0} already exists. Food request denied..
        /// </summary>
        internal static string FoodRequestDeniedBarcodeExists {
            get {
                return ResourceManager.GetString("FoodRequestDeniedBarcodeExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Food request not found.
        /// </summary>
        internal static string FoodRequestNotFound {
            get {
                return ResourceManager.GetString("FoodRequestNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No food requests found.
        /// </summary>
        internal static string FoodRequestsEmpty {
            get {
                return ResourceManager.GetString("FoodRequestsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Food Requests.
        /// </summary>
        internal static string FoodRequestsPageTitle {
            get {
                return ResourceManager.GetString("FoodRequestsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Food Request Status.
        /// </summary>
        internal static string FoodRequestsPickerTitle {
            get {
                return ResourceManager.GetString("FoodRequestsPickerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requests.
        /// </summary>
        internal static string FoodRequestsTabPageTitle {
            get {
                return ResourceManager.GetString("FoodRequestsTabPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barcode must be at least 8 characters long.
        /// </summary>
        internal static string FoodRequestValidationBarcode {
            get {
                return ResourceManager.GetString("FoodRequestValidationBarcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand is required.
        /// </summary>
        internal static string FoodRequestValidationBrand {
            get {
                return ResourceManager.GetString("FoodRequestValidationBrand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is required.
        /// </summary>
        internal static string FoodRequestValidationName {
            get {
                return ResourceManager.GetString("FoodRequestValidationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foods.
        /// </summary>
        internal static string FoodsTabTitle {
            get {
                return ResourceManager.GetString("FoodsTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barcode must be empty or between 8 and 13 characters.
        /// </summary>
        internal static string FoodValidationBarcode {
            get {
                return ResourceManager.GetString("FoodValidationBarcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calories must be between 0 and 900.
        /// </summary>
        internal static string FoodValidationCalories {
            get {
                return ResourceManager.GetString("FoodValidationCalories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carbohydrates must be between 0 and 100.
        /// </summary>
        internal static string FoodValidationCarbohydrates {
            get {
                return ResourceManager.GetString("FoodValidationCarbohydrates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fat must be between 0 and 100.
        /// </summary>
        internal static string FoodValidationFats {
            get {
                return ResourceManager.GetString("FoodValidationFats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image is required when creating a food.
        /// </summary>
        internal static string FoodValidationImage {
            get {
                return ResourceManager.GetString("FoodValidationImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is required.
        /// </summary>
        internal static string FoodValidationName {
            get {
                return ResourceManager.GetString("FoodValidationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proteins must be between 0 and 100.
        /// </summary>
        internal static string FoodValidationProtein {
            get {
                return ResourceManager.GetString("FoodValidationProtein", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You no longer have permission to perform this action..
        /// </summary>
        internal static string ForbiddenAction {
            get {
                return ResourceManager.GetString("ForbiddenAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot your password?.
        /// </summary>
        internal static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password.
        /// </summary>
        internal static string ForgotPasswordPageTitle {
            get {
                return ResourceManager.GetString("ForgotPasswordPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your email and we&apos;ll send you a reset code..
        /// </summary>
        internal static string ForgotPasswordSubtitle {
            get {
                return ResourceManager.GetString("ForgotPasswordSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong. Please try again..
        /// </summary>
        internal static string GenericErrorMessage {
            get {
                return ResourceManager.GetString("GenericErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to g.
        /// </summary>
        internal static string grams {
            get {
                return ResourceManager.GetString("grams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Handled.
        /// </summary>
        internal static string Handled {
            get {
                return ResourceManager.GetString("Handled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect password, please try again..
        /// </summary>
        internal static string IncorrectPassword {
            get {
                return ResourceManager.GetString("IncorrectPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong on the server. Please try again later..
        /// </summary>
        internal static string InternalServerError {
            get {
                return ResourceManager.GetString("InternalServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The credentials you entered are incorrect..
        /// </summary>
        internal static string InvalidCredentials {
            get {
                return ResourceManager.GetString("InvalidCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, enter a valid email address..
        /// </summary>
        internal static string InvalidEmailMessage {
            get {
                return ResourceManager.GetString("InvalidEmailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Email.
        /// </summary>
        internal static string InvalidEmailTitle {
            get {
                return ResourceManager.GetString("InvalidEmailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid or expired code. Please request a new one..
        /// </summary>
        internal static string InvalidOrExpiredCode {
            get {
                return ResourceManager.GetString("InvalidOrExpiredCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be 8–64 characters and include an uppercase letter, a lowercase letter, and a number..
        /// </summary>
        internal static string InvalidPasswordMessage {
            get {
                return ResourceManager.GetString("InvalidPasswordMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Password.
        /// </summary>
        internal static string InvalidPasswordTitle {
            get {
                return ResourceManager.GetString("InvalidPasswordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kcal.
        /// </summary>
        internal static string kcal {
            get {
                return ResourceManager.GetString("kcal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        internal static string LoadingText {
            get {
                return ResourceManager.GetString("LoadingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login failed.
        /// </summary>
        internal static string LoginFailedTitle {
            get {
                return ResourceManager.GetString("LoginFailedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address.
        /// </summary>
        internal static string LoginIdentifier {
            get {
                return ResourceManager.GetString("LoginIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string LoginText {
            get {
                return ResourceManager.GetString("LoginText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lunch.
        /// </summary>
        internal static string Lunch {
            get {
                return ResourceManager.GetString("Lunch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Macronutrients.
        /// </summary>
        internal static string Macronutrients {
            get {
                return ResourceManager.GetString("Macronutrients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management.
        /// </summary>
        internal static string ManagementTabTitle {
            get {
                return ResourceManager.GetString("ManagementTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Moderators.
        /// </summary>
        internal static string ManageModeratorsPageTitle {
            get {
                return ResourceManager.GetString("ManageModeratorsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You already have 3 pending food requests. Please wait until one is reviewed before submitting a new one..
        /// </summary>
        internal static string MaxFoodRequests {
            get {
                return ResourceManager.GetString("MaxFoodRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Food not found in this meal.
        /// </summary>
        internal static string MealFoodNotFound {
            get {
                return ResourceManager.GetString("MealFoodNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meal not found.
        /// </summary>
        internal static string MealNotFound {
            get {
                return ResourceManager.GetString("MealNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meals.
        /// </summary>
        internal static string MealsTabTitle {
            get {
                return ResourceManager.GetString("MealsTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Describe why you want to become a moderator....
        /// </summary>
        internal static string ModeratorRequestDescriptionPlaceholder {
            get {
                return ResourceManager.GetString("ModeratorRequestDescriptionPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The moderator request no longer exists..
        /// </summary>
        internal static string ModeratorRequestNotFound {
            get {
                return ResourceManager.GetString("ModeratorRequestNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no moderator requests.
        /// </summary>
        internal static string ModeratorRequestsEmpty {
            get {
                return ResourceManager.GetString("ModeratorRequestsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moderator Requests.
        /// </summary>
        internal static string ModeratorRequestsPageTitle {
            get {
                return ResourceManager.GetString("ModeratorRequestsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moderator Request Status.
        /// </summary>
        internal static string ModeratorRequestsPickerTitle {
            get {
                return ResourceManager.GetString("ModeratorRequestsPickerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request submitted.
        /// </summary>
        internal static string ModeratorRequestSubmitted {
            get {
                return ResourceManager.GetString("ModeratorRequestSubmitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request&apos;s description should be at least {0} characters long..
        /// </summary>
        internal static string ModeratorRequestValidation {
            get {
                return ResourceManager.GetString("ModeratorRequestValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No moderators found.
        /// </summary>
        internal static string ModeratorsEmpty {
            get {
                return ResourceManager.GetString("ModeratorsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moderators.
        /// </summary>
        internal static string ModeratorsTabPageTitle {
            get {
                return ResourceManager.GetString("ModeratorsTabPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mod Requests.
        /// </summary>
        internal static string ModRequestsTabPageTitle {
            get {
                return ResourceManager.GetString("ModRequestsTabPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have pending food requests.
        /// </summary>
        internal static string MyFoodRequestsEmpty {
            get {
                return ResourceManager.GetString("MyFoodRequestsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Food Requests.
        /// </summary>
        internal static string MyFoodRequestsPageTitle {
            get {
                return ResourceManager.GetString("MyFoodRequestsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Requests.
        /// </summary>
        internal static string MyRequestsTabPageTitle {
            get {
                return ResourceManager.GetString("MyRequestsTabPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New email.
        /// </summary>
        internal static string NewEmail {
            get {
                return ResourceManager.GetString("NewEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        internal static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New username.
        /// </summary>
        internal static string NewUsername {
            get {
                return ResourceManager.GetString("NewUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t have an account? Sign up.
        /// </summary>
        internal static string NoAccountText {
            get {
                return ResourceManager.GetString("NoAccountText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generic.
        /// </summary>
        internal static string NoBrandText {
            get {
                return ResourceManager.GetString("NoBrandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undefined.
        /// </summary>
        internal static string NoEndDate {
            get {
                return ResourceManager.GetString("NoEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t follow this user.
        /// </summary>
        internal static string NotFollowing {
            get {
                return ResourceManager.GetString("NotFollowing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ({1}).
        /// </summary>
        internal static string NutritionLabel {
            get {
                return ResourceManager.GetString("NutritionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moderators can apply only temporary restrictions.
        /// </summary>
        internal static string OnlyTemporaryRestrictions {
            get {
                return ResourceManager.GetString("OnlyTemporaryRestrictions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min. 8 characters.
        /// </summary>
        internal static string PasswordPlaceholder {
            get {
                return ResourceManager.GetString("PasswordPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password updated.
        /// </summary>
        internal static string PasswordUpdated {
            get {
                return ResourceManager.GetString("PasswordUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to per {0} g.
        /// </summary>
        internal static string perGrams {
            get {
                return ResourceManager.GetString("perGrams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick Image.
        /// </summary>
        internal static string PickImage {
            get {
                return ResourceManager.GetString("PickImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile picture required.
        /// </summary>
        internal static string ProfilePictureRequired {
            get {
                return ResourceManager.GetString("ProfilePictureRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to promote {0} to moderator?.
        /// </summary>
        internal static string PromoteUserToModeratorMessage {
            get {
                return ResourceManager.GetString("PromoteUserToModeratorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protein.
        /// </summary>
        internal static string Protein {
            get {
                return ResourceManager.GetString("Protein", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is already in {1}.
        /// </summary>
        internal static string RecipeAlreadyInList {
            get {
                return ResourceManager.GetString("RecipeAlreadyInList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipe not found.
        /// </summary>
        internal static string RecipeNotFound {
            get {
                return ResourceManager.GetString("RecipeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipes.
        /// </summary>
        internal static string RecipesTabTitle {
            get {
                return ResourceManager.GetString("RecipesTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request to become a moderator.
        /// </summary>
        internal static string RequestModeratorRole {
            get {
                return ResourceManager.GetString("RequestModeratorRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accepted.
        /// </summary>
        internal static string RequestStatusAccepted {
            get {
                return ResourceManager.GetString("RequestStatusAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Declined.
        /// </summary>
        internal static string RequestStatusDeclined {
            get {
                return ResourceManager.GetString("RequestStatusDeclined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending.
        /// </summary>
        internal static string RequestStatusPending {
            get {
                return ResourceManager.GetString("RequestStatusPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Password.
        /// </summary>
        internal static string ResetCodePageTitle {
            get {
                return ResourceManager.GetString("ResetCodePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the code we sent to your email and choose a new password..
        /// </summary>
        internal static string ResetCodeSubtitle {
            get {
                return ResourceManager.GetString("ResetCodeSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset password.
        /// </summary>
        internal static string ResetPasswordButton {
            get {
                return ResourceManager.GetString("ResetPasswordButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restrictions.
        /// </summary>
        internal static string RestrictionsTabPageTitle {
            get {
                return ResourceManager.GetString("RestrictionsTabPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        internal static string RestrictionStatusActive {
            get {
                return ResourceManager.GetString("RestrictionStatusActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactive.
        /// </summary>
        internal static string RestrictionStatusInactive {
            get {
                return ResourceManager.GetString("RestrictionStatusInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undefined.
        /// </summary>
        internal static string RestrictionStatusUndefined {
            get {
                return ResourceManager.GetString("RestrictionStatusUndefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Changes.
        /// </summary>
        internal static string SaveChanges {
            get {
                return ResourceManager.GetString("SaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Code.
        /// </summary>
        internal static string SendCode {
            get {
                return ResourceManager.GetString("SendCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sent.
        /// </summary>
        internal static string Sent {
            get {
                return ResourceManager.GetString("Sent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your session has expired. Please log in again..
        /// </summary>
        internal static string SessionExpired {
            get {
                return ResourceManager.GetString("SessionExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string SettingsTitle {
            get {
                return ResourceManager.GetString("SettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up failed.
        /// </summary>
        internal static string SignUpFailedTitle {
            get {
                return ResourceManager.GetString("SignUpFailedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up.
        /// </summary>
        internal static string SignUpText {
            get {
                return ResourceManager.GetString("SignUpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snack.
        /// </summary>
        internal static string Snack {
            get {
                return ResourceManager.GetString("Snack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit Request.
        /// </summary>
        internal static string SubmitRequest {
            get {
                return ResourceManager.GetString("SubmitRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unfollow.
        /// </summary>
        internal static string Unfollow {
            get {
                return ResourceManager.GetString("Unfollow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown User.
        /// </summary>
        internal static string UnknownUser {
            get {
                return ResourceManager.GetString("UnknownUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} updated.
        /// </summary>
        internal static string UpdatedFood {
            get {
                return ResourceManager.GetString("UpdatedFood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Food.
        /// </summary>
        internal static string UpdateFoodTitle {
            get {
                return ResourceManager.GetString("UpdateFoodTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username or email is already in use..
        /// </summary>
        internal static string UsernameOrEmailInUse {
            get {
                return ResourceManager.GetString("UsernameOrEmailInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username must be atleast {0} characters.
        /// </summary>
        internal static string UsernameTooShort {
            get {
                return ResourceManager.GetString("UsernameTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username updated.
        /// </summary>
        internal static string UsernameUpdated {
            get {
                return ResourceManager.GetString("UsernameUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username is already in use..
        /// </summary>
        internal static string UsernameUse {
            get {
                return ResourceManager.GetString("UsernameUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not found.
        /// </summary>
        internal static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        internal static string WelcomeText {
            get {
                return ResourceManager.GetString("WelcomeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
